{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"dataFileNil"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/openweathersdk\/apierror\/responsevalidationfailurereason\/datafilenil"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.daksh.OpenWeatherSDK\/documentation\/OpenWeatherSDK\/APIError\/ResponseValidationFailureReason\/dataFileNil","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The data file containing the server response did not exist."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"dataFileNil"}],"title":"APIError.ResponseValidationFailureReason.dataFileNil","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"s:14OpenWeatherSDK8APIErrorO31ResponseValidationFailureReasonO11dataFileNilyA2EmF","modules":[{"name":"OpenWeatherSDK"}]},"hierarchy":{"paths":[["doc:\/\/com.daksh.OpenWeatherSDK\/documentation\/OpenWeatherSDK","doc:\/\/com.daksh.OpenWeatherSDK\/documentation\/OpenWeatherSDK\/APIError","doc:\/\/com.daksh.OpenWeatherSDK\/documentation\/OpenWeatherSDK\/APIError\/ResponseValidationFailureReason"]]},"references":{"doc://com.daksh.OpenWeatherSDK/documentation/OpenWeatherSDK":{"role":"collection","title":"OpenWeatherSDK","abstract":[],"identifier":"doc:\/\/com.daksh.OpenWeatherSDK\/documentation\/OpenWeatherSDK","kind":"symbol","type":"topic","url":"\/documentation\/openweathersdk"},"doc://com.daksh.OpenWeatherSDK/documentation/OpenWeatherSDK/APIError":{"role":"symbol","title":"APIError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"APIError"}],"abstract":[{"type":"codeVoice","code":"APIError"},{"type":"text","text":" is the error type returned. It encompasses a few different types of errors, each with"},{"type":"text","text":" "},{"type":"text","text":"their own associated reasons."}],"identifier":"doc:\/\/com.daksh.OpenWeatherSDK\/documentation\/OpenWeatherSDK\/APIError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"APIError"}],"url":"\/documentation\/openweathersdk\/apierror"},"doc://com.daksh.OpenWeatherSDK/documentation/OpenWeatherSDK/APIError/ResponseValidationFailureReason":{"role":"symbol","title":"APIError.ResponseValidationFailureReason","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ResponseValidationFailureReason"}],"abstract":[{"type":"text","text":"The underlying reason the "},{"type":"codeVoice","code":".responseValidationFailed"},{"type":"text","text":" error occurred."}],"identifier":"doc:\/\/com.daksh.OpenWeatherSDK\/documentation\/OpenWeatherSDK\/APIError\/ResponseValidationFailureReason","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ResponseValidationFailureReason"}],"url":"\/documentation\/openweathersdk\/apierror\/responsevalidationfailurereason"},"doc://com.daksh.OpenWeatherSDK/documentation/OpenWeatherSDK/APIError/ResponseValidationFailureReason/dataFileNil":{"role":"symbol","title":"APIError.ResponseValidationFailureReason.dataFileNil","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"dataFileNil"}],"abstract":[{"type":"text","text":"The data file containing the server response did not exist."}],"identifier":"doc:\/\/com.daksh.OpenWeatherSDK\/documentation\/OpenWeatherSDK\/APIError\/ResponseValidationFailureReason\/dataFileNil","kind":"symbol","type":"topic","url":"\/documentation\/openweathersdk\/apierror\/responsevalidationfailurereason\/datafilenil"}}}